### ISSUE TITLE
Error when running stack trace for XWIKI-14711 with frame level 4

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/EvoCrash-demo#6]
context:
* With XWiki 9.8
* stacktrace from  https://jira.xwiki.org/browse/XWIKI-14711

stacktrace:

```
2017-09-20 13:30:48,765 [http://localhost:8080/xwiki/bin/edit/XWiki/XWikiServerTest/?xpage=editobject&xaction=addObject&className=WikiManager.WikiTemplateClass] ERROR .o.i.DefaultObservationManager - Failed to send event [org.xwiki.bridge.event.DocumentUpdatedEvent@8b696558] to listener [org.xwiki.wiki.internal.descriptor.listener.WikiDescriptorListener@3d4d06c4] 
java.lang.NullPointerException: Null keys are not supported!
	at org.infinispan.cache.impl.CacheImpl.assertKeyNotNull(CacheImpl.java:227)
	at org.infinispan.cache.impl.CacheImpl.remove(CacheImpl.java:550)
	at org.infinispan.cache.impl.CacheImpl.remove(CacheImpl.java:546)
	at org.xwiki.cache.infinispan.internal.InfinispanCache.remove(InfinispanCache.java:85)
	at org.xwiki.wiki.internal.manager.WikiDescriptorCache.remove(WikiDescriptorCache.java:120)
	at org.xwiki.wiki.internal.descriptor.listener.WikiDescriptorListener.removeExistingDescriptor(WikiDescriptorListener.java:114)
	at org.xwiki.wiki.internal.descriptor.listener.WikiDescriptorListener.onEvent(WikiDescriptorListener.java:92)
	at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:304)
	at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:269)
	at com.xpn.xwiki.XWiki.saveDocument(XWiki.java:1777)
	at com.xpn.xwiki.api.Document.saveDocument(Document.java:2509)
	at com.xpn.xwiki.api.Document.save(Document.java:2395)
	at com.xpn.xwiki.api.Document.save(Document.java:2384)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:567)
	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:142)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:106)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluateInternal(DefaultVelocityEngine.java:259)
	at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:222)
	at com.xpn.xwiki.render.DefaultVelocityManager.evaluate(DefaultVelocityManager.java:361)
	at com.xpn.xwiki.internal.template.InternalTemplateManager.evaluateContent(InternalTemplateManager.java:806)
	at com.xpn.xwiki.internal.template.InternalTemplateManager.render(InternalTemplateManager.java:682)
	at com.xpn.xwiki.internal.template.InternalTemplateManager.lambda$renderFromSkin$0(InternalTemplateManager.java:657)
	at com.xpn.xwiki.internal.security.authorization.DefaultAuthorExecutor.call(DefaultAuthorExecutor.java:85)
	at com.xpn.xwiki.internal.template.InternalTemplateManager.renderFromSkin(InternalTemplateManager.java:656)
	at com.xpn.xwiki.internal.template.InternalTemplateManager.renderFromSkin(InternalTemplateManager.java:635)
	at com.xpn.xwiki.internal.template.InternalTemplateManager.render(InternalTemplateManager.java:621)
	at com.xpn.xwiki.internal.template.DefaultTemplateManager.render(DefaultTemplateManager.java:78)
	at com.xpn.xwiki.XWiki.evaluateTemplate(XWiki.java:2120)
	at com.xpn.xwiki.web.Utils.parseTemplate(Utils.java:180)
	at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:463)
	at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:210)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at com.xpn.xwiki.web.ActionFilter.doFilter(ActionFilter.java:112)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.wysiwyg.filter.ConversionFilter.doFilter(ConversionFilter.java:127)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.container.servlet.filters.internal.SetHTTPHeaderFilter.doFilter(SetHTTPHeaderFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.container.servlet.filters.internal.SavedRequestRestorerFilter.doFilter(SavedRequestRestorerFilter.java:208)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.container.servlet.filters.internal.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:111)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.resource.servlet.RoutingFilter.doFilter(RoutingFilter.java:134)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)
2017-09-20 13:30:50,819 [http://localhost:8080/xwiki/bin/save/XWiki/XWikiServerTest/WebHome] ERROR .o.i.DefaultObservationManager - Failed to send event [org.xwiki.bridge.event.DocumentUpdatedEvent@8b696558] to listener [org.xwiki.wiki.internal.descriptor.listener.WikiDescriptorListener@3d4d06c4] 
java.lang.NullPointerException: Null keys are not supported!
	at org.infinispan.cache.impl.CacheImpl.assertKeyNotNull(CacheImpl.java:227)
	at org.infinispan.cache.impl.CacheImpl.remove(CacheImpl.java:550)
	at org.infinispan.cache.impl.CacheImpl.remove(CacheImpl.java:546)
	at org.xwiki.cache.infinispan.internal.InfinispanCache.remove(InfinispanCache.java:85)
	at org.xwiki.wiki.internal.manager.WikiDescriptorCache.remove(WikiDescriptorCache.java:120)
	at org.xwiki.wiki.internal.descriptor.listener.WikiDescriptorListener.removeExistingDescriptor(WikiDescriptorListener.java:114)
	at org.xwiki.wiki.internal.descriptor.listener.WikiDescriptorListener.onEvent(WikiDescriptorListener.java:92)
	at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:304)
	at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:269)
	at com.xpn.xwiki.XWiki.saveDocument(XWiki.java:1777)
	at com.xpn.xwiki.web.SaveAction.save(SaveAction.java:190)
	at com.xpn.xwiki.web.SaveAction.action(SaveAction.java:232)
	at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:446)
	at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:210)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at com.xpn.xwiki.web.ActionFilter.doFilter(ActionFilter.java:112)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.wysiwyg.filter.ConversionFilter.doFilter(ConversionFilter.java:127)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.container.servlet.filters.internal.SavedRequestRestorerFilter.doFilter(SavedRequestRestorerFilter.java:208)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.container.servlet.filters.internal.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:111)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:203)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73)
	at com.xpn.xwiki.web.ActionFilter.doFilter(ActionFilter.java:102)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.wysiwyg.filter.ConversionFilter.doFilter(ConversionFilter.java:124)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.container.servlet.filters.internal.SetHTTPHeaderFilter.doFilter(SetHTTPHeaderFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.container.servlet.filters.internal.SavedRequestRestorerFilter.doFilter(SavedRequestRestorerFilter.java:208)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.container.servlet.filters.internal.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:111)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.xwiki.resource.servlet.RoutingFilter.doFilter(RoutingFilter.java:134)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)
```

Results:

```
[…]
lineFitness: 0.0
currentFitness: 0.4411764705882353

lineFitness: 0.0
currentFitness: 0.4411764705882353

lineFitness: 0.0
currentFitness: 0.4411764705882353

Best individual has fitness: 0.4411764705882353
Worst individual has fitness: 4.5


* EvoCrash: the generated stack trace: 

org.xwiki.wiki.internal.manager.WikiDescriptorCache.remove(WikiDescriptorCache.java:120)
sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:748)

* EvoCrash: the generated test case: 
CacheManager cacheManager0 = mock(CacheManager.class, new ViolatedAssumptionAnswer());
Class<MemberCandidacy.CandidateType> class0 = MemberCandidacy.CandidateType.class;
Class<MemberCandidacy.CandidateType> class1 = MemberCandidacy.CandidateType.class;
Class<MemberCandidacy.CandidateType> class2 = MemberCandidacy.CandidateType.class;
Class<MemberCandidacy.CandidateType> class3 = MemberCandidacy.CandidateType.class;
Object object0 = new Object();
String string0 = "";
Injector.inject(string0, (Class<?>) class0, string0, (Object) class3);
Class<String> class4 = String.class;
Injector.validateBean(class2, (Class<?>) class3);
DefaultWikiDescriptor defaultWikiDescriptor0 = null;
String string1 = "";
String string2 = null;
WikiDescriptorCache wikiDescriptorCache0 = new WikiDescriptorCache();
Injector.inject(wikiDescriptorCache0, (Class<?>) WikiDescriptorCache.class, "cacheManager", (Object) cacheManager0);
Injector.validateBean(wikiDescriptorCache0, (Class<?>) WikiDescriptorCache.class);
Class<Integer> class5 = Integer.class;
Injector.inject(string2, (Class<?>) class5, string1, (Object) defaultWikiDescriptor0);
Class<MemberCandidacy.Status> class6 = MemberCandidacy.Status.class;
Injector.validateBean(class6, (Class<?>) class0);
int int0 = (-2618);
Class<MemberCandidacy.CandidateType> class7 = MemberCandidacy.CandidateType.class;
String string3 = "";
Class<Locale.LanguageRange> class8 = Locale.LanguageRange.class;
Class<Locale.LanguageRange> class9 = Locale.LanguageRange.class;
Class<MemberCandidacy.CandidateType> class10 = MemberCandidacy.CandidateType.class;
Class<MemberCandidacy.CandidateType> class11 = MemberCandidacy.CandidateType.class;
Class<Integer> class12 = Integer.class;
Class<Object> class13 = Object.class;
String string4 = "bN@;&Y&+fw";
Injector.inject(class8, (Class<?>) class13, string4, (Object) wikiDescriptorCache0);
Class<MemberCandidacy.Status> class14 = MemberCandidacy.Status.class;
Class<DefaultWikiDescriptor> class15 = DefaultWikiDescriptor.class;
Injector.validateBean(class4, (Class<?>) class12);
wikiDescriptorCache0.remove(defaultWikiDescriptor0);
String string5 = "\"\"`aV.S.}SuTRFW$ZP";
wikiDescriptorCache0.addFromId(string5, defaultWikiDescriptor0);
wikiDescriptorCache0.getFromId(string0);

GGA was done in 601!<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

! Budget exceeded
! Unable to cover goal 0 org.crash.client.crashcoverage.CrashCoverageTestFitness@2a6384de
* Search finished after 605s, 604 statements, best individual has fitness 0.0
* Covered 0/1 goals
* Target exception was set to: java.lang.NullPointerException
* EvoCrash: The target call is either public or protected!
The retrived call(s) to inject in the tests are:
remove
[MASTER] 10:29:54.219 [logback-1] WARN  TimeController - Phase INITIALIZATION lasted too long, 497 seconds more than allowed.
* Target exception was set to: java.lang.NullPointerException
* EvoCrash: The target call is either public or protected!
The retrived call(s) to inject in the tests are:
remove
* Minimizing test suite
* Going to analyze the coverage criteria
* Coverage analysis for criterion CRASH
* Target exception was set to: java.lang.NullPointerException
* EvoCrash: The target call is either public or protected!
The retrived call(s) to inject in the tests are:
remove
* Coverage of criterion CRASH: 0%
* Total number of goals: 1
* Number of covered goals: 0
* Generated 0 tests with total length 0
* Resulting test suite's coverage: 0%
* Generating assertions
* Resulting test suite's mutation score: 0%
* Compiling and checking tests
* Permissions denied during test execution: 
 - java.lang.RuntimePermission: 
        writeFileDescriptor: 1
* Writing JUnit test case 'WikiDescriptorCache_ESTest' to GGA-tests
* Done!
```

**Comment by pderakhshanfar** [comment]
As we can see, the best value for the fitness function is 0.4 for this execution, and it could not achieve to fitness function 0 (complete crash replication). The closest generated stack trace has only frame level 5 (org.xwiki.wiki.internal.manager.WikiDescriptorCache.remove(WikiDescriptorCache.java:120)). EvoCrash may achieve fitness function 0 if we give more search budget (more than 10 minutes). The other explanation is that EvoCrash got stock in local optima, and it could not have any progress after getting to 0.4 fitness function. In this situation, we should improve the EvoCrash search process by updating the evolving operators and fitness function.
